import { Account, AppSettings, Category, RecurringRule, Transaction } from '../types/finance';

export const DEFAULT_SETTINGS: AppSettings = {
  currency: 'CZK',
  budgetStartDay: 15,
  overdraftLimitInHaler: 2000000, // Výše kontokorentu: 20 000 Kč
  minReserveInHaler: 2000000, // Pro zpětnou kompatibilitu
  forecastMonths: 12,
  roundAmounts: false,
};

export const DEFAULT_CATEGORIES: Category[] = [
  // Příjmy
  {
    id: 'cat_income',
    name: 'Příjmy',
    type: 'income',
    parentId: null,
    color: '#16a34a',
    icon: 'TrendingUp',
    sortOrder: 1,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'sub_income_salary',
    name: 'Mzda',
    type: 'income',
    parentId: 'cat_income',
    color: '#16a34a',
    icon: 'Briefcase',
    sortOrder: 1,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'sub_income_other',
    name: 'Ostatní příjmy',
    type: 'income',
    parentId: 'cat_income',
    color: '#22c55e',
    icon: 'Coins',
    sortOrder: 2,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },

  // Bydlení
  {
    id: 'cat_housing',
    name: 'Bydlení',
    type: 'expense',
    parentId: null,
    color: '#0284c7',
    icon: 'Home',
    sortOrder: 2,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  { id: 'sub_housing_mortgage', name: 'Hypotéka', type: 'expense', parentId: 'cat_housing', color: '#0284c7', icon: 'Key', sortOrder: 1, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_housing_services', name: 'Služby', type: 'expense', parentId: 'cat_housing', color: '#0284c7', icon: 'FileText', sortOrder: 2, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_housing_electricity', name: 'Elektřina', type: 'expense', parentId: 'cat_housing', color: '#0284c7', icon: 'Zap', sortOrder: 3, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_housing_gas', name: 'Plyn', type: 'expense', parentId: 'cat_housing', color: '#0284c7', icon: 'Flame', sortOrder: 4, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_housing_internet', name: 'Telefon a internet', type: 'expense', parentId: 'cat_housing', color: '#0284c7', icon: 'Wifi', sortOrder: 5, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_housing_fees', name: 'Poplatky', type: 'expense', parentId: 'cat_housing', color: '#0284c7', icon: 'Receipt', sortOrder: 6, status: 'active', createdAt: '', updatedAt: '' },

  // Domácnost
  {
    id: 'cat_household',
    name: 'Domácnost',
    type: 'expense',
    parentId: null,
    color: '#0d9488',
    icon: 'ShoppingCart',
    sortOrder: 3,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  { id: 'sub_hh_food', name: 'Stravování', type: 'expense', parentId: 'cat_household', color: '#0d9488', icon: 'Utensils', sortOrder: 1, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_hh_drugstore', name: 'Drogerie', type: 'expense', parentId: 'cat_household', color: '#0d9488', icon: 'Sparkles', sortOrder: 2, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_hh_medicine', name: 'Léky', type: 'expense', parentId: 'cat_household', color: '#0d9488', icon: 'Pill', sortOrder: 3, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_hh_maintenance', name: 'Provoz domácnosti', type: 'expense', parentId: 'cat_household', color: '#0d9488', icon: 'Wrench', sortOrder: 4, status: 'active', createdAt: '', updatedAt: '' },

  // Osobní
  {
    id: 'cat_personal',
    name: 'Osobní',
    type: 'expense',
    parentId: null,
    color: '#6366f1',
    icon: 'Smile',
    sortOrder: 4,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  { id: 'sub_pers_leisure', name: 'Volný čas', type: 'expense', parentId: 'cat_personal', color: '#6366f1', icon: 'Coffee', sortOrder: 1, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_pers_sport', name: 'Sport', type: 'expense', parentId: 'cat_personal', color: '#6366f1', icon: 'Activity', sortOrder: 2, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_pers_it', name: 'IT', type: 'expense', parentId: 'cat_personal', color: '#6366f1', icon: 'Laptop', sortOrder: 3, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_pers_media', name: 'Média a předplatná', type: 'expense', parentId: 'cat_personal', color: '#6366f1', icon: 'Tv', sortOrder: 4, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_pers_other', name: 'Ostatní', type: 'expense', parentId: 'cat_personal', color: '#6366f1', icon: 'MoreHorizontal', sortOrder: 5, status: 'active', createdAt: '', updatedAt: '' },

  // Auto
  {
    id: 'cat_auto',
    name: 'Auto',
    type: 'expense',
    parentId: null,
    color: '#ea580c',
    icon: 'Car',
    sortOrder: 5,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  { id: 'sub_auto_leasing', name: 'Leasing', type: 'expense', parentId: 'cat_auto', color: '#ea580c', icon: 'CreditCard', sortOrder: 1, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_auto_fuel', name: 'Palivo', type: 'expense', parentId: 'cat_auto', color: '#ea580c', icon: 'Fuel', sortOrder: 2, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_auto_parking', name: 'Parkování', type: 'expense', parentId: 'cat_auto', color: '#ea580c', icon: 'SquareParking', sortOrder: 3, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_auto_ops', name: 'Provoz', type: 'expense', parentId: 'cat_auto', color: '#ea580c', icon: 'Settings2', sortOrder: 4, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_auto_service', name: 'Servis', type: 'expense', parentId: 'cat_auto', color: '#ea580c', icon: 'Wrench', sortOrder: 5, status: 'active', createdAt: '', updatedAt: '' },

  // Pojištění
  {
    id: 'cat_insurance',
    name: 'Pojištění',
    type: 'expense',
    parentId: null,
    color: '#dc2626',
    icon: 'Shield',
    sortOrder: 6,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  { id: 'sub_ins_household', name: 'Domácnost', type: 'expense', parentId: 'cat_insurance', color: '#dc2626', icon: 'ShieldAlert', sortOrder: 1, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_ins_sport', name: 'Sportovní vybavení', type: 'expense', parentId: 'cat_insurance', color: '#dc2626', icon: 'ShieldCheck', sortOrder: 2, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_ins_vehicle', name: 'Vozidlo', type: 'expense', parentId: 'cat_insurance', color: '#dc2626', icon: 'ShieldCheck', sortOrder: 3, status: 'active', createdAt: '', updatedAt: '' },
  { id: 'sub_ins_life', name: 'Životní pojištění', type: 'expense', parentId: 'cat_insurance', color: '#dc2626', icon: 'HeartPulse', sortOrder: 4, status: 'active', createdAt: '', updatedAt: '' },
];

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: 'demo_acc_checking',
    name: 'Běžný účet',
    type: 'checking',
    currency: 'CZK',
    initialBalanceInHaler: 8500000, // 85 000 Kč
    initialBalanceDate: '2026-09-01',
    isUsableCash: true,
    isNetWorth: true,
    isDefault: true,
    institution: 'Česká spořitelna',
    color: '#0284c7',
    sortOrder: 1,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'demo_acc_cash',
    name: 'Hotovost',
    type: 'cash',
    currency: 'CZK',
    initialBalanceInHaler: 540000, // 5 400 Kč
    initialBalanceDate: '2026-09-01',
    isUsableCash: true,
    isNetWorth: true,
    institution: 'Peněženka',
    color: '#14b8a6',
    sortOrder: 2,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'demo_acc_savings1',
    name: 'Spořicí účet',
    type: 'savings',
    currency: 'CZK',
    initialBalanceInHaler: 15000000, // 150 000 Kč
    initialBalanceDate: '2026-09-01',
    isUsableCash: true,
    isNetWorth: true,
    institution: 'Česká spořitelna',
    color: '#10b981',
    sortOrder: 3,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'demo_acc_savings2',
    name: 'Spořicí účet Air Bank',
    type: 'savings',
    currency: 'CZK',
    initialBalanceInHaler: 8000000, // 80 000 Kč
    initialBalanceDate: '2026-09-01',
    isUsableCash: true,
    isNetWorth: true,
    institution: 'Air Bank',
    color: '#84cc16',
    sortOrder: 4,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'demo_acc_pension',
    name: 'Doplňkové penzijní spoření',
    type: 'pension',
    currency: 'CZK',
    initialBalanceInHaler: 24000000, // 240 000 Kč
    initialBalanceDate: '2026-09-01',
    isUsableCash: false,
    isNetWorth: true,
    institution: 'Generali Penzijní společnost',
    color: '#f59e0b',
    sortOrder: 5,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'demo_acc_invest1',
    name: 'Investiční účet ČSOB Velmi odvážný',
    type: 'investment',
    currency: 'CZK',
    initialBalanceInHaler: 35000000, // 350 000 Kč
    currentMarketValueInHaler: 38500000, // 385 000 Kč
    marketValueUpdatedAt: '2026-09-10',
    initialBalanceDate: '2026-09-01',
    isUsableCash: false,
    isNetWorth: true,
    institution: 'ČSOB',
    color: '#8b5cf6',
    sortOrder: 6,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'demo_acc_invest2',
    name: 'Investiční účet ČSOB Odvážný',
    type: 'investment',
    currency: 'CZK',
    initialBalanceInHaler: 20000000, // 200 000 Kč
    currentMarketValueInHaler: 21500000, // 215 000 Kč
    marketValueUpdatedAt: '2026-09-10',
    initialBalanceDate: '2026-09-01',
    isUsableCash: false,
    isNetWorth: true,
    institution: 'ČSOB',
    color: '#6366f1',
    sortOrder: 7,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const DEMO_RECURRING_RULES: RecurringRule[] = [
  {
    id: 'rec_salary',
    title: 'Mzda',
    amountInHaler: 6500000, // 65 000 Kč
    type: 'income',
    frequency: 'monthly',
    dayOfMonth: 20,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_income',
    subcategoryId: 'sub_income_salary',
    note: 'Měsíční mzda ze zaměstnání',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_mortgage',
    title: 'Hypotéka',
    amountInHaler: 1850000, // 18 500 Kč
    type: 'expense',
    frequency: 'monthly',
    dayOfMonth: 16,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_housing_mortgage',
    note: 'Splátka hypotéky ČS',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_services',
    title: 'Služby a fond oprav',
    amountInHaler: 420000, // 4 200 Kč
    type: 'expense',
    frequency: 'monthly',
    dayOfMonth: 17,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_housing_services',
    note: 'SVJ zálohy',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_electricity',
    title: 'Elektřina',
    amountInHaler: 280000, // 2 800 Kč
    type: 'expense',
    frequency: 'monthly',
    dayOfMonth: 20,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_housing_electricity',
    note: 'ČEZ záloha',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_gas',
    title: 'Plyn',
    amountInHaler: 150000, // 1 500 Kč
    type: 'expense',
    frequency: 'monthly',
    dayOfMonth: 22,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_housing_gas',
    note: 'Innogy záloha',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_internet',
    title: 'Telefon a internet',
    amountInHaler: 110000, // 1 100 Kč
    type: 'expense',
    frequency: 'monthly',
    dayOfMonth: 25,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_housing',
    subcategoryId: 'sub_housing_internet',
    note: 'T-Mobile optika a tarif',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_media',
    title: 'Předplatná a streamy',
    amountInHaler: 65000, // 650 Kč
    type: 'expense',
    frequency: 'monthly',
    dayOfMonth: 1,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_personal',
    subcategoryId: 'sub_pers_media',
    note: 'Netflix + Spotify + YouTube Premium',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_insurance',
    title: 'Životní pojištění',
    amountInHaler: 180000, // 1 800 Kč
    type: 'expense',
    frequency: 'monthly',
    dayOfMonth: 5,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_insurance',
    subcategoryId: 'sub_ins_life',
    note: 'Kooperativa životní pojištění',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_save_transfer',
    title: 'Pravidelný převod na spoření',
    amountInHaler: 1000000, // 10 000 Kč
    type: 'transfer',
    frequency: 'monthly',
    dayOfMonth: 21,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    targetAccountId: 'demo_acc_savings1',
    note: 'Spoření pro finanční polštář',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'rec_invest_transfer',
    title: 'Pravidelný investiční vklad',
    amountInHaler: 500000, // 5 000 Kč
    type: 'transfer',
    frequency: 'monthly',
    dayOfMonth: 22,
    startDate: '2026-09-15',
    sourceAccountId: 'demo_acc_checking',
    targetAccountId: 'demo_acc_invest1',
    note: 'Měsíční nákup ETF fondů',
    isActive: true,
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'demo_tx_1',
    title: 'Nákup potravin na víkend',
    amountInHaler: 185000, // 1 850 Kč
    date: '2026-09-16',
    sequence: 1,
    type: 'expense',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_household',
    subcategoryId: 'sub_hh_food',
    status: 'executed',
    actualAmountInHaler: 185000,
    note: 'Rohlik.cz',
    createdAt: '2026-09-16T10:00:00Z',
    updatedAt: '2026-09-16T10:00:00Z',
  },
  {
    id: 'demo_tx_2',
    title: 'Tankování Benzina',
    amountInHaler: 210000, // 2 100 Kč
    date: '2026-09-18',
    sequence: 1,
    type: 'expense',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_auto',
    subcategoryId: 'sub_auto_fuel',
    status: 'executed',
    actualAmountInHaler: 210000,
    note: 'Plná nádrž',
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-18T14:00:00Z',
  },
  {
    id: 'demo_tx_3',
    title: 'Nákup lékárna',
    amountInHaler: 42000, // 420 Kč
    date: '2026-09-21',
    sequence: 1,
    type: 'expense',
    sourceAccountId: 'demo_acc_cash',
    categoryId: 'cat_household',
    subcategoryId: 'sub_hh_medicine',
    status: 'executed',
    actualAmountInHaler: 42000,
    note: 'Vitamíny',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-21T09:00:00Z',
  },
  {
    id: 'demo_tx_4',
    title: 'Plánovaný servis auta před zimou',
    amountInHaler: 1200000, // 12 000 Kč
    date: '2026-11-05',
    sequence: 1,
    type: 'expense',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_auto',
    subcategoryId: 'sub_auto_service',
    status: 'planned',
    plannedAmountInHaler: 1200000,
    note: 'Přezutí pneu, výměna oleje a brzd',
    createdAt: '2026-09-12T00:00:00Z',
    updatedAt: '2026-09-12T00:00:00Z',
  },
  {
    id: 'demo_tx_5',
    title: 'Vánoční dárky',
    amountInHaler: 1500000, // 15 000 Kč
    date: '2026-12-10',
    sequence: 1,
    type: 'expense',
    sourceAccountId: 'demo_acc_checking',
    categoryId: 'cat_personal',
    subcategoryId: 'sub_pers_other',
    status: 'planned',
    plannedAmountInHaler: 1500000,
    note: 'Plánovaný rozpočet na Vánoce',
    createdAt: '2026-09-12T00:00:00Z',
    updatedAt: '2026-09-12T00:00:00Z',
  }
];
